export const DEFAULT_SENSOR_RADIUS=2, MAX_SENSOR_RADIUS=4, LEGACY_POSITION_COUNT=24;
export const FEATURE_CATEGORIES=20, HIDDEN_SIZE=16, OUTPUT_SIZE=5, POSITION_COUNT=80;
export const STATE_FEATURE_OFFSET=POSITION_COUNT*FEATURE_CATEGORIES;
export const CLIMATE_FEATURE_OFFSET=STATE_FEATURE_OFFSET+8;
export const CLIMATE_FEATURE_COUNT=17, INPUT_SIZE=CLIMATE_FEATURE_OFFSET+CLIMATE_FEATURE_COUNT;
export const LEGACY_INPUT_SIZE=272, V2_INPUT_SIZE=284, BRAIN_SCHEMA_VERSION=3;
export const enum SenseChannel { Occupancy=1, Heading=2, Danger=4, Resources=8, Terrain=16, Temperature=32, Fertility=64, Internal=128 }
export const DEFAULT_SENSE_CHANNELS=SenseChannel.Occupancy|SenseChannel.Heading|SenseChannel.Danger|SenseChannel.Resources|SenseChannel.Internal|SenseChannel.Temperature|SenseChannel.Fertility;
export const MAX_INFERENCE_BUDGET=400;
export interface BrainSeed { schemaVersion?:number;inputWeights:number[][];hiddenBias:number[];outputWeights:number[][];outputBias:number[]; }
const randomWeight=(scale:number,random=Math.random)=>(random()*2-1)*scale;
const legacyFeature=(index:number):boolean=>index<LEGACY_POSITION_COUNT*FEATURE_CATEGORIES&&index%FEATURE_CATEGORIES<11||index>=STATE_FEATURE_OFFSET&&index<STATE_FEATURE_OFFSET+8;

export function clampPerception(radius:number,channels:number):{radius:number;channels:number;cost:number}{let safe=Math.max(1,Math.min(MAX_SENSOR_RADIUS,Math.round(radius))),mask=channels&255;const count=()=>((safe*2+1)**2-1)*Math.max(1,popcount(mask));while(count()>MAX_INFERENCE_BUDGET&&safe>1)safe--;for(let bit=128;count()>MAX_INFERENCE_BUDGET&&bit>=1;bit>>=1)if(mask&bit)mask&=~bit;return{radius:safe,channels:mask,cost:count()};}
const popcount=(value:number)=>{let count=0;while(value){value&=value-1;count++;}return count;};

export class Nnue {
  inputWeights:Float32Array[];hiddenBias:Float32Array;outputWeights:Float32Array[];outputBias:Float32Array;
  private accumulator:Float32Array;private output=new Float32Array(OUTPUT_SIZE);private shared=false;private active:number[]=[];
  constructor(seed?:BrainSeed|Nnue,random=Math.random){if(seed instanceof Nnue){this.inputWeights=seed.inputWeights;this.hiddenBias=seed.hiddenBias;this.outputWeights=seed.outputWeights;this.outputBias=seed.outputBias;this.shared=true;seed.shared=true;}else{if(seed)validateSeed(seed);this.inputWeights=seed?migrateInputs(seed):Array.from({length:INPUT_SIZE},(_,index)=>Float32Array.from({length:HIDDEN_SIZE},()=>legacyFeature(index)?randomWeight(.12,random):0));this.hiddenBias=seed?Float32Array.from(seed.hiddenBias):Float32Array.from({length:HIDDEN_SIZE},()=>randomWeight(.05,random));this.outputWeights=seed?seed.outputWeights.map(row=>Float32Array.from(row)):Array.from({length:OUTPUT_SIZE},()=>Float32Array.from({length:HIDDEN_SIZE},()=>randomWeight(.18,random)));this.outputBias=seed?Float32Array.from(seed.outputBias):Float32Array.from({length:OUTPUT_SIZE},()=>randomWeight(.05,random));}this.accumulator=new Float32Array(this.hiddenBias);}
  clone():Nnue{return new Nnue(this);}
  toSeed():BrainSeed{return{schemaVersion:BRAIN_SCHEMA_VERSION,inputWeights:this.inputWeights.map(row=>Array.from(row)),hiddenBias:Array.from(this.hiddenBias),outputWeights:this.outputWeights.map(row=>Array.from(row)),outputBias:Array.from(this.outputBias)};}
  evaluate(features:readonly number[]):Float32Array{let oldIndex=0,newIndex=0;while(oldIndex<this.active.length||newIndex<features.length){const oldFeature=this.active[oldIndex]??INPUT_SIZE,newFeature=features[newIndex]??INPUT_SIZE;if(oldFeature===newFeature){oldIndex++;newIndex++;}else if(oldFeature<newFeature){this.apply(oldFeature,-1);oldIndex++;}else{this.apply(newFeature,1);newIndex++;}}this.active.length=features.length;for(let index=0;index<features.length;index++)this.active[index]=features[index]!;for(let output=0;output<OUTPUT_SIZE;output++){let value=this.outputBias[output]??0,row=this.outputWeights[output]!;for(let hidden=0;hidden<HIDDEN_SIZE;hidden++)value+=Math.max(0,this.accumulator[hidden]??0)*(row[hidden]??0);this.output[output]=value;}return this.output;}
  action(features:readonly number[]):number{const output=this.evaluate(features);let best=0;for(let i=1;i<output.length;i++)if(output[i]!>output[best]!)best=i;return best;}
  train(features:readonly number[],target:number,rate:number):void{const scores=this.evaluate(features),maximum=Math.max(...scores),probabilities=Array.from(scores,score=>Math.exp(score-maximum)),total=probabilities.reduce((sum,value)=>sum+value,0),hiddenGradient=new Float32Array(HIDDEN_SIZE);for(let output=0;output<OUTPUT_SIZE;output++){const gradient=(probabilities[output]??0)/total-(output===target?1:0),row=this.outputWeights[output]!;for(let hidden=0;hidden<HIDDEN_SIZE;hidden++){hiddenGradient[hidden]=(hiddenGradient[hidden]??0)+gradient*(row[hidden]??0);row[hidden]=(row[hidden]??0)-rate*gradient*Math.max(0,this.accumulator[hidden]??0);}this.outputBias[output]=(this.outputBias[output]??0)-rate*gradient;}for(let hidden=0;hidden<HIDDEN_SIZE;hidden++){if((this.accumulator[hidden]??0)<=0)continue;const gradient=hiddenGradient[hidden]??0;this.hiddenBias[hidden]=(this.hiddenBias[hidden]??0)-rate*gradient;for(const feature of features){const row=this.inputWeights[feature];if(row)row[hidden]=(row[hidden]??0)-rate*gradient;}}this.reset();}
  mutate(probability=.03,magnitude=.2):void{this.ensureOwned();let changed=false;const perturb=(values:Float32Array)=>{for(let i=0;i<values.length;i++)if(Math.random()<probability){values[i]=(values[i]??0)+randomWeight(magnitude);changed=true;}};this.inputWeights.forEach(perturb);perturb(this.hiddenBias);this.outputWeights.forEach(perturb);perturb(this.outputBias);if(!changed)this.outputBias[Math.floor(Math.random()*OUTPUT_SIZE)]!+=randomWeight(magnitude);this.reset();}
  private apply(feature:number,sign:number):void{const weights=this.inputWeights[feature];if(!weights)return;for(let hidden=0;hidden<HIDDEN_SIZE;hidden++)this.accumulator[hidden]=(this.accumulator[hidden]??0)+sign*(weights[hidden]??0);}
  private ensureOwned():void{if(!this.shared)return;this.inputWeights=this.inputWeights.map(row=>row.slice());this.hiddenBias=this.hiddenBias.slice();this.outputWeights=this.outputWeights.map(row=>row.slice());this.outputBias=this.outputBias.slice();this.shared=false;}
  private reset():void{this.active.length=0;this.accumulator.set(this.hiddenBias);}
}
function migrateInputs(seed:BrainSeed):Float32Array[]{if(seed.inputWeights.length===INPUT_SIZE)return seed.inputWeights.map(row=>Float32Array.from(row));const result=Array.from({length:INPUT_SIZE},()=>new Float32Array(HIDDEN_SIZE));for(let square=0;square<LEGACY_POSITION_COUNT;square++)for(let category=0;category<11;category++)result[square*FEATURE_CATEGORIES+category]!.set(seed.inputWeights[square*11+category]!);for(let state=0;state<8;state++)result[STATE_FEATURE_OFFSET+state]!.set(seed.inputWeights[264+state]!);if(seed.inputWeights.length===V2_INPUT_SIZE)for(let climate=0;climate<12;climate++)result[CLIMATE_FEATURE_OFFSET+climate]!.set(seed.inputWeights[272+climate]!);return result;}
function validateSeed(seed:BrainSeed):void{const rows=seed.inputWeights.length;if(rows!==LEGACY_INPUT_SIZE&&rows!==V2_INPUT_SIZE&&rows!==INPUT_SIZE)throw new Error("Invalid brain input row count: "+rows);if(seed.hiddenBias.length!==HIDDEN_SIZE||seed.outputBias.length!==OUTPUT_SIZE||seed.outputWeights.length!==OUTPUT_SIZE)throw new Error("Invalid brain hidden/output dimensions");if(seed.inputWeights.some(row=>row.length!==HIDDEN_SIZE)||seed.outputWeights.some(row=>row.length!==HIDDEN_SIZE))throw new Error("Invalid brain row width");}
