#define WIN32_LEAN_AND_MEAN
#include <windows.h>
#include <algorithm>
#include <array>
#include <chrono>
#include <cmath>
#include <cstdint>
#include <random>
#include <string>
#include <vector>

constexpr int WorldW=1024,WorldH=640,InitialPopulation=10000;
enum Terrain:uint8_t{Plains,Fertile,Desert,Water,Mountain};
enum Resource:uint8_t{None,Plant,Carrion,Mineral};
struct Brain{std::array<float,8*16> input{};std::array<float,16> bias{};std::array<float,16*5> output{};};
struct Organism{int x{},y{},energy{12000},minerals{},age{},parent{-1};uint8_t direction{},radius{2},channels{0xff};float stress{};bool alive{true};Brain brain;};
struct World{
 std::vector<uint8_t> terrain=std::vector<uint8_t>(WorldW*WorldH),resource=std::vector<uint8_t>(WorldW*WorldH);
 std::vector<uint16_t> amount=std::vector<uint16_t>(WorldW*WorldH);std::vector<int32_t> owner=std::vector<int32_t>(WorldW*WorldH,-1);std::vector<uint32_t> pixels=std::vector<uint32_t>(WorldW*WorldH);
 std::vector<Organism> organisms;uint64_t ticks{};uint32_t seed{1};double measuredTps{};bool running{true};
 static uint32_t hash(int x,int y,uint32_t s){uint32_t v=(uint32_t(x)^s)*0x45d9f3bu^(uint32_t(y)+s)*0x119de1f3u;v=(v^(v>>16))*0x45d9f3bu;return v^(v>>16);}
 void generate(uint32_t nextSeed){seed=nextSeed;std::fill(owner.begin(),owner.end(),-1);std::fill(resource.begin(),resource.end(),None);std::fill(amount.begin(),amount.end(),0);for(int y=0;y<WorldH;y++)for(int x=0;x<WorldW;x++){int i=y*WorldW+x;float coarse=float(hash(x/24,y/24,seed))/4294967295.f,detail=float(hash(x,y,seed^0x9e3779b9u))/4294967295.f,v=coarse*.78f+detail*.22f;terrain[i]=v<.13f?Water:v>.9f?Mountain:v<.3f?Desert:v>.67f?Fertile:Plains;if(terrain[i]==Fertile&&detail>.7f){resource[i]=Plant;amount[i]=600;}else if(terrain[i]<Water&&detail<.018f){resource[i]=Mineral;amount[i]=1000;}}spawn();}
 bool passable(int x,int y)const{return x>=0&&y>=0&&x<WorldW&&y<WorldH&&terrain[y*WorldW+x]!=Water&&terrain[y*WorldW+x]!=Mountain;}
 Brain seedBrain(){Brain b;std::mt19937 rng(seed);std::uniform_real_distribution<float>d(-.12f,.12f);for(auto&v:b.input)v=d(rng);for(auto&v:b.output)v=d(rng);return b;}
 void spawn(){organisms.clear();organisms.reserve(InitialPopulation);Brain base=seedBrain();for(int i=0;i<InitialPopulation;i++){int x=hash(i,3,seed)%WorldW,y=hash(i,7,seed)%WorldH;if(!passable(x,y)||owner[y*WorldW+x]>=0)continue;Organism o;o.x=x;o.y=y;o.direction=i&3;o.brain=base;owner[y*WorldW+x]=int32_t(organisms.size());organisms.push_back(std::move(o));}}
 uint8_t decide(Organism&o){std::array<float,8> f{};f[0]=float(o.energy)/12000.f;f[1]=o.stress;f[2]=float(o.x)/WorldW;f[3]=float(o.y)/WorldH;float phase=float(ticks%24000)/24000.f,wave=std::sin(phase*6.2831853f),lat=1.f-2.f*o.y/float(WorldH-1),temp=std::clamp(.5f+.5f*lat*wave,0.f,1.f);f[4]=temp;f[5]=.35f+temp;for(int dy=-o.radius;dy<=o.radius;dy++)for(int dx=-o.radius;dx<=o.radius;dx++){if(!dx&&!dy)continue;int x=o.x+dx,y=o.y+dy;if(x>=0&&y>=0&&x<WorldW&&y<WorldH){int i=y*WorldW+x;if(resource[i]==Plant)f[6]+=1.f/(1+std::abs(dx)+std::abs(dy));if(owner[i]>=0)f[7]+=1.f;}}std::array<float,16> h{};for(int j=0;j<16;j++){float v=o.brain.bias[j];for(int i=0;i<8;i++)v+=f[i]*o.brain.input[i*16+j];h[j]=std::max(0.f,v);}int best=4;float score=-1e30f;for(int k=0;k<5;k++){float v=0;for(int j=0;j<16;j++)v+=h[j]*o.brain.output[k*16+j];if(v>score){score=v;best=k;}}return uint8_t(best);}
 void step(){ticks++;float phase=float(ticks%24000)/24000.f,wave=std::sin(phase*6.2831853f);for(size_t id=0;id<organisms.size();id++){auto&o=organisms[id];if(!o.alive)continue;o.age++;float lat=1.f-2.f*o.y/float(WorldH-1),temp=std::clamp(.5f+.5f*lat*wave,0.f,1.f);o.stress=std::max(0.f,o.stress+(temp<.35f?.001f+(.35f-temp)*.012f:temp>.65f?.001f+(temp-.65f)*.012f:-.004f));o.energy-=2+(terrain[o.y*WorldW+o.x]==Desert?4:0);if(o.energy<=0||o.age>100000){die(int(id));continue;}if((ticks+id)%8==0)o.direction=decide(o);if(o.direction<4){static constexpr int dx[4]={0,0,-1,1},dy[4]={-1,1,0,0};int nx=o.x+dx[o.direction],ny=o.y+dy[o.direction];if(passable(nx,ny)&&owner[ny*WorldW+nx]<0){owner[o.y*WorldW+o.x]=-1;o.x=nx;o.y=ny;owner[ny*WorldW+nx]=int(id);o.energy-=15;}}consume(o);}}
 void consume(Organism&o){for(auto [dx,dy]:std::array<std::pair<int,int>,4>{{{0,-1},{0,1},{-1,0},{1,0}}}){int x=o.x+dx,y=o.y+dy;if(x<0||y<0||x>=WorldW||y>=WorldH)continue;int i=y*WorldW+x;if(resource[i]==Plant&&amount[i]){int used=std::min<int>(100,amount[i]);amount[i]-=uint16_t(used);o.energy+=used*40;if(!amount[i])resource[i]=None;}else if(resource[i]==Mineral&&amount[i]){int used=std::min<int>(100,amount[i]);amount[i]-=uint16_t(used);o.minerals+=used;if(!amount[i])resource[i]=None;}}}
 void die(int id){auto&o=organisms[id];if(!o.alive)return;o.alive=false;int i=o.y*WorldW+o.x;owner[i]=-1;resource[i]=Carrion;amount[i]=uint16_t(std::min(65535,200+o.energy/20));}
 void render(){static constexpr uint32_t tc[5]={0x0030432e,0x00365b2b,0x0032526c,0x005f3e1a,0x005a524d},rc[4]={0,0x0037b418,0x00324b8b,0x0052bdd7};for(int i=0;i<WorldW*WorldH;i++)pixels[i]=resource[i]?rc[resource[i]]:tc[terrain[i]];for(auto&o:organisms)if(o.alive)pixels[o.y*WorldW+o.x]=0x00eb9334;}
};
World world;BITMAPINFO bitmapInfo{};int selected=-1;
void paint(HDC dc,HWND hwnd){RECT r;GetClientRect(hwnd,&r);world.render();StretchDIBits(dc,0,0,r.right-280,r.bottom,0,0,WorldW,WorldH,world.pixels.data(),&bitmapInfo,DIB_RGB_COLORS,SRCCOPY);SetBkMode(dc,TRANSPARENT);SetTextColor(dc,RGB(235,240,245));std::wstring text=L"LIFE ENGINE NATIVE\n\nSpace: pause\nR: regenerate\nClick: inspect\n\nOrganisms: "+std::to_wstring(world.organisms.size())+L"\nTicks: "+std::to_wstring(world.ticks)+L"\nTPS: "+std::to_wstring(int(world.measuredTps))+L"\nSeed: "+std::to_wstring(world.seed);RECT panel{r.right-260,30,r.right-10,r.bottom};DrawTextW(dc,text.c_str(),-1,&panel,DT_LEFT|DT_TOP);if(selected>=0&&selected<int(world.organisms.size())){auto&o=world.organisms[selected];std::wstring info=L"\n\nSelected #"+std::to_wstring(selected)+L"\nEnergy: "+std::to_wstring(o.energy)+L"\nMinerals: "+std::to_wstring(o.minerals)+L"\nStress: "+std::to_wstring(o.stress)+L"\nRadius: "+std::to_wstring(o.radius);DrawTextW(dc,info.c_str(),-1,&panel,DT_LEFT|DT_TOP);}}
LRESULT CALLBACK windowProc(HWND hwnd,UINT msg,WPARAM wp,LPARAM lp){if(msg==WM_DESTROY){PostQuitMessage(0);return 0;}if(msg==WM_KEYDOWN){if(wp==VK_SPACE)world.running=!world.running;else if(wp=='R')world.generate(world.seed+1);return 0;}if(msg==WM_LBUTTONDOWN){RECT r;GetClientRect(hwnd,&r);int viewWidth=std::max(1,int(r.right)-280),viewHeight=std::max(1,int(r.bottom));int x=int(LOWORD(lp))*WorldW/viewWidth;int y=int(HIWORD(lp))*WorldH/viewHeight;if(x>=0&&x<WorldW&&y>=0&&y<WorldH)selected=world.owner[y*WorldW+x];return 0;}if(msg==WM_PAINT){PAINTSTRUCT ps;HDC dc=BeginPaint(hwnd,&ps);paint(dc,hwnd);EndPaint(hwnd,&ps);return 0;}return DefWindowProcW(hwnd,msg,wp,lp);}
int WINAPI wWinMain(HINSTANCE instance,HINSTANCE,LPWSTR,int show){bitmapInfo.bmiHeader.biSize=sizeof(BITMAPINFOHEADER);bitmapInfo.bmiHeader.biWidth=WorldW;bitmapInfo.bmiHeader.biHeight=-WorldH;bitmapInfo.bmiHeader.biPlanes=1;bitmapInfo.bmiHeader.biBitCount=32;bitmapInfo.bmiHeader.biCompression=BI_RGB;WNDCLASSW wc{};wc.lpfnWndProc=windowProc;wc.hInstance=instance;wc.lpszClassName=L"LifeEngineNative";wc.hCursor=LoadCursor(nullptr,IDC_ARROW);wc.hbrBackground=CreateSolidBrush(RGB(18,29,41));RegisterClassW(&wc);HWND hwnd=CreateWindowExW(0,wc.lpszClassName,L"Life Engine Native C++",WS_OVERLAPPEDWINDOW,CW_USEDEFAULT,CW_USEDEFAULT,1400,850,nullptr,nullptr,instance,nullptr);ShowWindow(hwnd,show);world.generate(1);MSG msg{};auto last=std::chrono::steady_clock::now(),metric=last;int steps=0;double accumulator=0;while(msg.message!=WM_QUIT){while(PeekMessageW(&msg,nullptr,0,0,PM_REMOVE)){TranslateMessage(&msg);DispatchMessageW(&msg);}auto now=std::chrono::steady_clock::now();accumulator+=std::chrono::duration<double>(now-last).count()*60.;last=now;if(world.running)while(accumulator>=1){world.step();accumulator-=1;steps++;}double elapsed=std::chrono::duration<double>(now-metric).count();if(elapsed>=1){world.measuredTps=steps/elapsed;steps=0;metric=now;}InvalidateRect(hwnd,nullptr,FALSE);Sleep(1);}return 0;}
