import './style.css';
import { climateAt } from './core/climate';
import type { BrainSeed } from './core/nnue';
import type { WorkerCommand,WorkerResponse } from './core/protocol';
import type { OrganismInspection } from './core/simulation';
import { CELL_COLORS,CellType,ResourceType,TerrainType,type Metrics } from './core/types';
import { terrainProductivity } from './core/world';

const app=document.querySelector<HTMLDivElement>('#app');if(!app)throw new Error('Missing app root');
app.innerHTML=`<main class='shell'><header><div><span class='eyebrow'>EVOLUTION, ACCELERATED</span><h1>Life Engine <em>NNUE</em></h1></div><div class='status'><i></i><span id='run-state'>Running</span></div></header><section class='stage'><canvas id='world'></canvas><div class='legend'><span>Terrain + resources + evolving organisms</span></div></section><aside><section class='metrics'><article><span>ORGANISMS</span><strong id='organisms'>0</strong></article><article><span>ACTUAL TPS</span><strong id='actual-tps'>0</strong></article><article><span>RENDER FPS</span><strong id='render-fps'>0</strong></article><article><span>SEASON</span><strong id='season'>Spring</strong></article></section><section class='panel controls'><div class='control-title'><h3>Simulation</h3><button id='toggle'>Pause</button></div><label>Requested simulation TPS <output id='speed-value'>60</output><input id='speed' type='range' min='1' max='120' value='60'></label><label>Overlay <select id='overlay'><option value='terrain'>Terrain</option><option value='resources'>Resources</option><option value='productivity'>Productivity</option><option value='climate'>Climate</option></select></label><div class='button-grid'><button id='reset'>Reset life</button><button id='regenerate'>New seeded world</button></div></section><section class='panel tools'><h3>World tools</h3><div class='tool-row'><button class='tool active' data-tool='inspect'>Inspect</button><button class='tool' data-tool='pan'>Pan</button><button class='tool' data-tool='plant'>Plant</button><button class='tool' data-tool='carrion'>Carrion</button><button class='tool' data-tool='mineral'>Mineral</button><button class='tool' data-tool='fertile'>Fertile</button><button class='tool' data-tool='desert'>Desert</button><button class='tool' data-tool='water'>Water</button><button class='tool' data-tool='mountain'>Mountain</button></div><p>Wheel to zoom. Terrain affects passability and physiology, never steering.</p></section><section class='panel observatory'><div class='control-title'><h3>Evolution Observatory</h3><button id='clear-selection'>Clear</button></div><div id='observation' class='observation-empty'>Select a creature.</div></section><footer><span id='population'></span><span id='performance'></span></footer></aside></main>`;
const W=1024,H=640,canvas=document.querySelector<HTMLCanvasElement>('#world')!,ctx=canvas.getContext('2d',{alpha:false})!,back=document.createElement('canvas');back.width=W;back.height=H;const backCtx=back.getContext('2d',{alpha:false})!,image=backCtx.createImageData(W,H);
let cells:Uint8Array<ArrayBufferLike>=new Uint8Array(W*H),owners:Int32Array<ArrayBufferLike>=new Int32Array(W*H),terrain:Uint8Array<ArrayBufferLike>=new Uint8Array(W*H),resources:Uint8Array<ArrayBufferLike>=new Uint8Array(W*H),amounts:Uint16Array<ArrayBufferLike>=new Uint16Array(W*H);owners.fill(-1);
let metrics:Metrics|undefined,inspection:OrganismInspection|undefined,zoom=2,cameraX=0,cameraY=0,running=true,pixelsDirty=false,renderAckPending=false,dragging=false,dragX=0,dragY=0,tool='inspect',overlay='terrain',frames=0,lastFps=performance.now();
const worker=new Worker(new URL('./simulation.worker.ts',import.meta.url),{type:'module'}),send=(data:WorkerCommand)=>worker.postMessage(data);
const hex=(value:string)=>{const probe=document.createElement('canvas').getContext('2d')!;probe.fillStyle=value;probe.fillRect(0,0,1,1);return Array.from(probe.getImageData(0,0,1,1).data.slice(0,3));};const cellColors=Object.fromEntries(Object.entries(CELL_COLORS).map(([key,value])=>[key,hex(value)]));
const terrainColors=[[46,67,48],[43,91,54],[108,82,50],[26,62,95],[77,82,90]],resourceColors=[[0,0,0],[24,180,55],[139,75,50],[215,189,82]];
function pixel(index:number):void{let color=terrainColors[terrain[index]!]??terrainColors[0]!;if(overlay==='productivity'){const p=terrainProductivity(terrain[index] as TerrainType);color=[30+80*p,35+120*p,35+40*p];}else if(overlay==='climate'&&metrics){const c=climateAt(Math.floor(index/W),H,metrics.ticks);color=[40+180*c.temperature,35+80*c.fertility,55+140*(1-c.temperature)];}if(resources[index]!==ResourceType.None&&(overlay==='resources'||cells[index]===CellType.Empty))color=resourceColors[resources[index]!]!;if(cells[index]!==CellType.Empty)color=cellColors[cells[index]!]??[255,255,255];const offset=index*4;image.data[offset]=color[0]!;image.data[offset+1]=color[1]!;image.data[offset+2]=color[2]!;image.data[offset+3]=255;}
function refresh(indices?:Uint32Array):void{if(indices)for(const index of indices)pixel(index);else for(let index=0;index<cells.length;index++)pixel(index);pixelsDirty=true;}
worker.onmessage=({data}:MessageEvent<WorkerResponse>)=>{if(data.type==='full-snapshot'){({cells,owners,terrain,resources,resourceAmount:amounts}=data);refresh();}else if(data.type==='cell-delta'){for(let i=0;i<data.indices.length;i++){const index=data.indices[i]!;cells[index]=data.cells[i]!;owners[index]=data.owners[i]!;terrain[index]=data.terrain[i]!;resources[index]=data.resources[i]!;amounts[index]=data.resourceAmount[i]!;pixel(index);}pixelsDirty=true;renderAckPending=true;}else if(data.type==='metrics'){metrics=data.metrics;renderMetrics();}else if(data.type==='selection'){inspection=data.inspection;renderEcologyInspection();}else if(data.type==='error')console.error(data.message);};
function resize(){const box=canvas.getBoundingClientRect(),scale=devicePixelRatio||1;canvas.width=Math.floor(box.width*scale);canvas.height=Math.floor(box.height*scale);ctx.setTransform(scale,0,0,scale,0,0);}
function frame(now:number){if(pixelsDirty){backCtx.putImageData(image,0,0);pixelsDirty=false;}ctx.fillStyle='#121d29';ctx.fillRect(0,0,canvas.clientWidth,canvas.clientHeight);ctx.imageSmoothingEnabled=zoom<1;ctx.drawImage(back,cameraX,cameraY,W*zoom,H*zoom);if(renderAckPending){renderAckPending=false;send({type:'render-ack'});}frames++;if(now-lastFps>=1000){document.querySelector('#render-fps')!.textContent=String(Math.round(frames*1000/(now-lastFps)));frames=0;lastFps=now;}requestAnimationFrame(frame);}
function renderMetrics(){if(!metrics)return;document.querySelector('#organisms')!.textContent=metrics.organisms.toLocaleString();document.querySelector('#actual-tps')!.textContent=metrics.measuredTps.toFixed(1);document.querySelector('#season')!.textContent=metrics.season;document.querySelector('#population')!.textContent=`Plant ${metrics.plantEaters} · Scavenger ${metrics.scavengers} · Mineral ${metrics.mineralEaters} · Predators ${metrics.predators}`;document.querySelector('#performance')!.textContent=`NNUE ${metrics.nnueEvaluations.toLocaleString()} · ${(metrics.memoryEstimate/1048576).toFixed(1)} MB · backlog ${metrics.renderBacklog}`;}
function renderInspection(){const root=document.querySelector<HTMLElement>('#observation')!;if(!inspection){root.className='observation-empty';root.textContent='Select a creature.';return;}const o=inspection;root.className='';root.innerHTML=`<div class='organism-heading'><strong>#${o.id}</strong><span class='life-badge ${o.alive?'alive':'dead'}'>${o.alive?'Alive':'Dead'}</span></div><div class='inspection-stats'><span>Generation<strong>${o.generation}</strong></span><span>Energy<strong>${(o.energy/1000).toFixed(1)}</strong></span><span>Minerals<strong>${o.minerals}</strong></span><span>Damage<strong>${o.damage}</strong></span><span>Stress<strong>${(o.thermalStress*100).toFixed(1)}%</strong></span><span>Radius<strong>${o.perceptionRadius}</strong></span></div><div class='rates'><span>Neural cost <b>${o.neuralCost}</b></span><span>Channels <b>0x${o.senseChannels.toString(16)}</b></span><span>Fertility <b>${o.fertility.toFixed(2)}×</b></span></div><h4>Mutations</h4><ul class='mutation-list'>${o.mutations.map(value=>`<li>${value}</li>`).join('')||'<li>None</li>'}</ul><h4>Neural action</h4><p>${o.action??'Static'}</p>`;}
function renderEcologyInspection(){const root=document.querySelector<HTMLElement>('#observation')!;if(!inspection){root.className='observation-empty';root.textContent='Select a creature.';return;}const o=inspection;root.className='';root.innerHTML=`<div class='organism-heading'><strong>#${o.id} · ${o.diet}</strong><span class='life-badge ${o.alive?'alive':'dead'}'>${o.alive?'Alive':'Dead'}</span></div><div class='inspection-stats'><span>Energy<strong>${(o.energy/1000).toFixed(1)}</strong></span><span>Minerals<strong>${o.minerals}</strong></span><span>Terrain<strong>${o.terrain}</strong></span><span>Resource<strong>${o.resource}</strong></span><span>Killer durability<strong>${o.attackDurability}</strong></span><span>Armor durability<strong>${o.armorDurability}</strong></span><span>Stress<strong>${(o.thermalStress*100).toFixed(1)}%</strong></span><span>Radius<strong>${o.perceptionRadius}</strong></span></div><div class='rates'><span>Metabolism <b>${o.metabolicCost.toFixed(1)}</b></span><span>Neural cost <b>${o.neuralCost}</b></span><span>Channels <b>0x${o.senseChannels.toString(16)}</b></span></div><h4>Mutations</h4><ul class='mutation-list'>${o.mutations.map(value=>`<li>${value}</li>`).join('')||'<li>None</li>'}</ul><h4>Neural action</h4><p>${o.action??'Static'}</p>`;}
const point=(event:PointerEvent):[number,number]=>{const box=canvas.getBoundingClientRect();return[Math.floor((event.clientX-box.left-cameraX)/zoom),Math.floor((event.clientY-box.top-cameraY)/zoom)];};
document.querySelector('#toggle')!.addEventListener('click',event=>{running=!running;send({type:'step-control',running});(event.currentTarget as HTMLButtonElement).textContent=running?'Pause':'Resume';});document.querySelector('#reset')!.addEventListener('click',()=>send({type:'reset'}));document.querySelector('#regenerate')!.addEventListener('click',()=>send({type:'regenerate',seed:Math.floor(Math.random()*0xffffffff)}));document.querySelector<HTMLInputElement>('#speed')!.addEventListener('input',event=>{const value=Number((event.target as HTMLInputElement).value);document.querySelector('#speed-value')!.textContent=String(value);send({type:'step-control',running,ticksPerSecond:value});});document.querySelector<HTMLSelectElement>('#overlay')!.addEventListener('change',event=>{overlay=(event.target as HTMLSelectElement).value;refresh();});document.querySelectorAll<HTMLButtonElement>('.tool').forEach(button=>button.addEventListener('click',()=>{document.querySelector('.tool.active')?.classList.remove('active');button.classList.add('active');tool=button.dataset.tool!;}));
canvas.addEventListener('pointerdown',event=>{if(tool==='pan'||event.button===1){dragging=true;dragX=event.clientX-cameraX;dragY=event.clientY-cameraY;return;}const[x,y]=point(event);if(tool==='inspect')send({type:'select',x,y});else if(tool==='plant'||tool==='carrion'||tool==='mineral')send({type:'paint-resource',x,y,resourceType:tool==='plant'?ResourceType.Plant:tool==='carrion'?ResourceType.Carrion:ResourceType.Mineral});else send({type:'paint-terrain',x,y,terrainType:tool==='fertile'?TerrainType.Fertile:tool==='desert'?TerrainType.Desert:tool==='water'?TerrainType.Water:TerrainType.Mountain});});canvas.addEventListener('pointermove',event=>{if(dragging){cameraX=event.clientX-dragX;cameraY=event.clientY-dragY;}});canvas.addEventListener('pointerup',()=>dragging=false);canvas.addEventListener('wheel',event=>{event.preventDefault();const box=canvas.getBoundingClientRect(),wx=(event.clientX-box.left-cameraX)/zoom,wy=(event.clientY-box.top-cameraY)/zoom;zoom=Math.max(.5,Math.min(16,zoom*(event.deltaY<0?1.2:1/1.2)));cameraX=event.clientX-box.left-wx*zoom;cameraY=event.clientY-box.top-wy*zoom;},{passive:false});document.querySelector('#clear-selection')!.addEventListener('click',()=>{inspection=undefined;renderInspection();});
let seed:BrainSeed|undefined;try{const response=await fetch('/trained-brain.json');if(response.ok)seed=await response.json() as BrainSeed;}catch{}send({type:'initialize',seed,width:W,height:H});send({type:'step-control',running:true,ticksPerSecond:60});window.addEventListener('resize',resize);resize();requestAnimationFrame(frame);
